spring.application.name=registry

spring.config.import=configserver:http://192.168.100.23:8001

spring.cloud.config.uri=http://192.168.100.23:8001
spring.cloud.config.fail-fast=true
spring.cloud.config.password=admin
spring.cloud.config.username=user

eureka.instance.preferIpAddress=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.server.waitTimeInMsWhenSyncEmpty=0
eureka.server.peer-node-read-timeout-ms=100000


